### PR TITLE
Implements other fiat currencies

### PR DESCRIPTION
**Pull request by grunch**
Currently only works with USD fiat currency, with this fix the plugin
works with the fiat currency indicated by the admin via settings

### CODE REVIEW

**Comment by joaodealmeida** [comment]
Not sure if bitcoinaverage API accepts all fiat currencies at this point.

**Comment by grunch** [comment]
I'm currently using it with argentinian pesos (ARS) and it works perfectly

**Comment by joaodealmeida** [comment]
But we need some kind of error handling if a certain currency is not accepted by bitcoinaverage's ticker method.

**Comment by leblitzdick** [comment]
In order  to calculate correctly other currencies, you should set the variable ticker to the desired value in Lnd_wrapper.php in function getLivePrice () - for me that would be BTCEUR and LTCEUR - not very elegant but works for me...

**Comment by joaodealmeida** [comment]
@leblitzdick I haven't had the time I wanted to work on this project. Feel free to push a PR with those changes and I'll happily accept it.

**Pull request closed without merging**
